a=int(input("Enter 1st number"))
b=int(input("Enter 2nd number"))
print("ADDITION:it returns the addition",a+b)
print("SUBTRACTION:it returns the subtraction",a-b)
print("MULTIPLICATION:it returns the multiplication",a*b)
print("EXPONENTIAL:it returns a to the power b",a**b)
print("DIVISION:it returns the quotient",a/b)
print("MODULUS:it returns the remainder",a%b)
print("FLOOR DIVISION:it removes the decimal point and returns only the whole number",a//b)
